# Generated by Django 3.2.25 on 2024-06-05 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StationVehicle',
            fields=[
                ('station_vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('owner_name', models.CharField(max_length=45)),
                ('vehicle_num', models.CharField(max_length=45)),
                ('photo', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('starting_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('police_station_id', models.IntegerField()),
                ('status', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'station_vehicle',
                'managed': False,
            },
        ),
    ]
