# Generated by Django 3.2.25 on 2024-05-06 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_name', models.CharField(max_length=45)),
                ('vehicle_number', models.CharField(max_length=45)),
                ('colour', models.CharField(max_length=45)),
                ('model', models.CharField(max_length=45)),
                ('owner_name', models.CharField(max_length=45)),
                ('owner_contact', models.CharField(max_length=45)),
                ('insurance_details', models.CharField(max_length=45)),
                ('registration_date', models.DateField()),
                ('last_service_date', models.DateField()),
                ('mileage', models.CharField(max_length=45)),
                ('pollution_certificate', models.CharField(max_length=45)),
                ('engine_number', models.CharField(max_length=45)),
                ('photo', models.CharField(max_length=45)),
                ('user_id', models.IntegerField()),
                ('expiry_date', models.DateField()),
                ('status', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'vehicle',
                'managed': False,
            },
        ),
    ]
