# Generated by Django 3.2.25 on 2024-05-06 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuspiciousActivity',
            fields=[
                ('suspicious_activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('case_no', models.CharField(max_length=45)),
                ('case_details', models.CharField(max_length=45)),
                ('case_date', models.DateField()),
            ],
            options={
                'db_table': 'suspicious_activity',
                'managed': False,
            },
        ),
    ]
