# Generated by Django 3.2.25 on 2024-05-06 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapdealerRequest',
            fields=[
                ('scrapdealer_request_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'scrapdealer_request',
                'managed': False,
            },
        ),
    ]
