# Generated by Django 3.2.25 on 2024-05-06 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('certificate_id', models.AutoField(primary_key=True, serialize=False)),
                ('holder_name', models.CharField(max_length=45)),
                ('issue_date', models.CharField(max_length=45)),
                ('vehicle_no', models.CharField(max_length=45)),
                ('certificate_no', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'certificate',
                'managed': False,
            },
        ),
    ]
